version: '3.8'

services:
  doobie:
    build: .
    volumes:
      - ./.:/build
    entrypoint: ["/bin/bash", "-c"]
    command:
    - |
      cd /build
      sbt evicted > evicted.out
      sbt dependencyTree > deptree.out
